export enum NotificationType {
  UPCOMING_APPOINTMENT = 'UPCOMING_APPOINTMENT',
  CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT',
  CREATE_APPOINTMENT = 'CREATE_APPOINTMENT',
  HEALTH_GOAL_NOTIFICATION = 'HEALTH_GOAL_NOTIFICATION',
  GET_ANSWER_NOTIFICATION = 'GET_ANSWER_NOTIFICATION',
  THANK_YOU_NOTIFICATION = 'THANK_YOU_NOTIFICATION',
  AGREED_NOTIFICATION = 'AGREED_NOTIFICATION',
  CANCEL_OVERTIME_PENDING_GOAL = 'CANCEL_OVERTIME_PENDING_GOAL',
}

export interface INotification {
  id: string;
  title: string;
  isRead: boolean;
  content: string;
  notificationType: NotificationType;
  createdAt: Date;
  updatedAt: Date;
}
